name: Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
